services:
  redis:
    image: redis:7.4.0
    restart: always
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redisdata:
    driver: local
    driver_opts:
      type: none
      device: ../opencti_persistent_volumes/redisdata
      o: bind

