services:
  nginx:
    env_file: "../envs/service-nginx.env"
    image: nginx:latest
    volumes:
      - ../nginx_conf/nginx_ssl:/etc/nginx/ssl/
      - ../nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx_conf/templates:/etc/nginx/templates
    environment:
      - NGINX_DOMAIN=${NGINX_DOMAIN}
      - NGINX_PROXY_PASS=${NGINX_PROXY_PASS}
    depends_on:
      opencti:
        condition: service_healthy
    restart: always
    healthcheck:
      test: curl -s http://nginx >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    ports:
      - "443:443"
      - "80:80"

