services:
  connector-alienvault:
    image: opencti/connector-alienvault:rolling
    env_file: "../envs/connector-alienvault.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_DURATION_PERIOD=${CONNECTOR_ALIENVAULT_DURATION_PERIOD}
      - CONNECTOR_ID=${CONNECTOR_ALIENVAULT_ID}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_ALIENVAULT_LOG_LEVEL}
      - CONNECTOR_NAME=${CONNECTOR_ALIENVAULT_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_ALIENVAULT_SCOPE}
      - ALIENVAULT_BASE_URL=${ALIENVAULT_BASE_URL}
      - ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES=${ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES}
      - ALIENVAULT_GUESS_CVE=${ALIENVAULT_GUESS_CVE}
      - ALIENVAULT_GUESS_MALWARE=${ALIENVAULT_GUESS_MALWARE}
      - ALIENVAULT_PULSE_START_TIMESTAMP=${ALIENVAULT_PULSE_START_TIMESTAMP}
      - ALIENVAULT_REPORT_STATUS=${ALIENVAULT_REPORT_STATUS}
      - ALIENVAULT_TLP=${ALIENVAULT_TLP}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

