services:
  connector-opencti_datasets:
    image: opencti/connector-opencti:rolling
    env_file: "../envs/connector-opencti_datasets.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_CONFIDENCE_LEVEL=${CONNECTOR_OPENCTI_DATASETS_CONFIDENCE_LEVEL}
      - CONNECTOR_ID=${CONNECTOR_OPENCTI_DATASETS_ID}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_OPENCTI_DATASETS_LOG_LEVEL}
      - CONNECTOR_NAME=${CONNECTOR_OPENCTI_DATASETS_NAME}
      - CONNECTOR_RUN_AND_TERMINATE=${CONNECTOR_OPENCTI_DATASETS_RUN_AND_TERMINATE}
      - CONNECTOR_SCOPE=${CONNECTOR_OPENCTI_DATASETS_SCOPE}
      - CONNECTOR_UPDATE_EXISTING_DATA=${CONNECTOR_OPENCTI_DATASETS_UPDATE_EXISTING_DATA}
      - CONFIG_COMPANIES_FILE_URL=${CONFIG_OPENCTI_DATASETS_COMPANIES_FILE_URL}
      - CONFIG_GEOGRAPHY_FILE_URL=${CONFIG_OPENCTI_DATASETS_GEOGRAPHY_FILE_URL}
      - CONFIG_INTERVAL=${CONFIG_OPENCTI_DATASETS_INTERVAL}
      - CONFIG_REMOVE_CREATOR=${CONFIG_OPENCTI_DATASETS_REMOVE_CREATOR}
      - CONFIG_SECTORS_FILE_URL=${CONFIG_OPENCTI_DATASETS_SECTORS_FILE_URL}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

