services:
  connector-malwarebazaar:
    image: opencti/connector-malwarebazaar-recent-additions:rolling
    env_file: "../envs/connector-malwarebazaar.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MALWAREBAZAAR_ID}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_MALWAREBAZAAR_LOG_LEVEL}
      - CONNECTOR_NAME=${CONNECTOR_MALWAREBAZAAR_NAME}
      - MALWAREBAZAAR_RECENT_ADDITIONS_API_URL=${MALWAREBAZAAR_RECENT_ADDITIONS_API_URL}
      - MALWAREBAZAAR_RECENT_ADDITIONS_COOLDOWN_SECONDS=${MALWAREBAZAAR_RECENT_ADDITIONS_COOLDOWN_SECONDS}
      - MALWAREBAZAAR_RECENT_ADDITIONS_INCLUDE_REPORTERS=${MALWAREBAZAAR_RECENT_ADDITIONS_INCLUDE_REPORTERS}
      - MALWAREBAZAAR_RECENT_ADDITIONS_INCLUDE_TAGS=${MALWAREBAZAAR_RECENT_ADDITIONS_INCLUDE_TAGS}
      - MALWAREBAZAAR_RECENT_ADDITIONS_LABELS=${MALWAREBAZAAR_RECENT_ADDITIONS_LABELS}
      - MALWAREBAZAAR_RECENT_ADDITIONS_LABELS_COLOR=${MALWAREBAZAAR_RECENT_ADDITIONS_LABELS_COLOR}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

