services:
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID}
      - CONNECTOR_TYPE=${CONNECTOR_EXPORT_FILE_STIX_TYPE}
      - CONNECTOR_NAME=${CONNECTOR_EXPORT_FILE_STIX_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_EXPORT_FILE_STIX_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_EXPORT_FILE_STIX_LOG_LEVEL}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID}
      - CONNECTOR_TYPE=${CONNECTOR_EXPORT_FILE_CSV_TYPE}
      - CONNECTOR_NAME=${CONNECTOR_EXPORT_FILE_CSV_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_EXPORT_FILE_CSV_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_EXPORT_FILE_CSV_LOG_LEVEL}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-export-file-txt:
    image: opencti/connector-export-file-txt:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_TXT_ID}
      - CONNECTOR_TYPE=${CONNECTOR_EXPORT_FILE_TXT_TYPE}
      - CONNECTOR_NAME=${CONNECTOR_EXPORT_FILE_TXT_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_EXPORT_FILE_TXT_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_EXPORT_FILE_TXT_LOG_LEVEL}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=${CONNECTOR_IMPORT_FILE_STIX_TYPE}
      - CONNECTOR_NAME=${CONNECTOR_IMPORT_FILE_STIX_NAME}
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=${CONNECTOR_IMPORT_FILE_STIX_VALIDATE_BEFORE_IMPORT}
      - CONNECTOR_SCOPE=${CONNECTOR_IMPORT_FILE_STIX_SCOPE}
      - CONNECTOR_AUTO=${CONNECTOR_IMPORT_FILE_STIX_AUTO}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_IMPORT_FILE_STIX_LOG_LEVEL}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-import-document:
    image: opencti/connector-import-document:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=${CONNECTOR_IMPORT_DOCUMENT_TYPE}
      - CONNECTOR_NAME=${CONNECTOR_IMPORT_DOCUMENT_NAME}
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=${CONNECTOR_IMPORT_DOCUMENT_VALIDATE_BEFORE_IMPORT}
      - CONNECTOR_SCOPE=${CONNECTOR_IMPORT_DOCUMENT_SCOPE}
      - CONNECTOR_AUTO=${CONNECTOR_IMPORT_DOCUMENT_AUTO}
      - CONNECTOR_ONLY_CONTEXTUAL=${CONNECTOR_IMPORT_DOCUMENT_ONLY_CONTEXTUAL}
      - CONNECTOR_CONFIDENCE_LEVEL=${CONNECTOR_IMPORT_DOCUMENT_CONFIDENCE_LEVEL}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_IMPORT_DOCUMENT_LOG_LEVEL}
      - IMPORT_DOCUMENT_CREATE_INDICATOR=${IMPORT_DOCUMENT_CREATE_INDICATOR}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy
  connector-analysis:
    image: opencti/connector-import-document:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ANALYSIS_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=${CONNECTOR_ANALYSIS_TYPE}
      - CONNECTOR_NAME=${CONNECTOR_ANALYSIS_NAME}
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=${CONNECTOR_ANALYSIS_VALIDATE_BEFORE_IMPORT}
      - CONNECTOR_SCOPE=${CONNECTOR_ANALYSIS_SCOPE}
      - CONNECTOR_AUTO=${CONNECTOR_ANALYSIS_AUTO}
      - CONNECTOR_ONLY_CONTEXTUAL=${CONNECTOR_ANALYSIS_ONLY_CONTEXTUAL}
      - CONNECTOR_CONFIDENCE_LEVEL=${CONNECTOR_ANALYSIS_CONFIDENCE_LEVEL}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_ANALYSIS_LOG_LEVEL}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

  connector-export_ttps_file_navigator:
    image: opencti/connector-export-ttps-file-navigator:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_TTPS_ID}
      - CONNECTOR_CONFIDENCE_LEVEL=${CONNECTOR_EXPORT_TTPS_CONFIDENCE_LEVEL}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_EXPORT_TTPS_LOG_LEVEL}
      - CONNECTOR_NAME=${CONNECTOR_EXPORT_TTPS_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_EXPORT_TTPS_SCOPE}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

  connector-import_file_misp:
    image: opencti/connector-import-file-misp:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_MISP_ID}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_IMPORT_MISP_LOG_LEVEL}
      - CONNECTOR_NAME=${CONNECTOR_IMPORT_MISP_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_IMPORT_MISP_SCOPE}
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=${CONNECTOR_IMPORT_MISP_VALIDATE_BEFORE_IMPORT}
      - MISP_IMPORT_FILE_CREATE_REPORTS=${MISP_IMPORT_FILE_CREATE_REPORTS}
      - MISP_IMPORT_FILE_REPORT_TYPE=${MISP_IMPORT_FILE_REPORT_TYPE}
      - MISP_IMPORT_FILE_CREATE_INDICATORS=${MISP_IMPORT_FILE_CREATE_INDICATORS}
      - MISP_IMPORT_FILE_CREATE_OBSERVABLES=${MISP_IMPORT_FILE_CREATE_OBSERVABLES}
      - MISP_IMPORT_FILE_CREATE_OBJECT_OBSERVABLES=${MISP_IMPORT_FILE_CREATE_OBJECT_OBSERVABLES}
      - MISP_IMPORT_FILE_CREATE_TAGS_AS_LABELS=${MISP_IMPORT_FILE_CREATE_TAGS_AS_LABELS}
      - MISP_IMPORT_FILE_GUESS_THREAT_FROM_TAGS=${MISP_IMPORT_FILE_GUESS_THREAT_FROM_TAGS}
      - MISP_IMPORT_FILE_AUTHOR_FROM_TAGS=${MISP_IMPORT_FILE_AUTHOR_FROM_TAGS}
      - MISP_IMPORT_FILE_IMPORT_TO_IDS_NO_SCORE=${MISP_IMPORT_FILE_IMPORT_TO_IDS_NO_SCORE}
      - MISP_IMPORT_FILE_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT=${MISP_IMPORT_FILE_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT}
      - MISP_IMPORT_FILE_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT_TRANSPARENT=${MISP_IMPORT_FILE_IMPORT_UNSUPPORTED_OBSERVABLES_AS_TEXT_TRANSPARENT}
      - MISP_IMPORT_FILE_IMPORT_WITH_ATTACHMENTS=${MISP_IMPORT_FILE_IMPORT_WITH_ATTACHMENTS}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

  connector-export_report_pdf:
    image: opencti/connector-export-report-pdf:rolling
    env_file: "../envs/connector-opencti_defaults.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_PDF_ID}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_EXPORT_PDF_LOG_LEVEL}
      - CONNECTOR_NAME=${CONNECTOR_EXPORT_PDF_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_EXPORT_PDF_SCOPE}
      - CONNECTOR_CONFIDENCE_LEVEL=${CONNECTOR_EXPORT_PDF_CONFIDENCE_LEVEL}
      - EXPORT_REPORT_PDF_PRIMARY_COLOR=${EXPORT_REPORT_PDF_PRIMARY_COLOR}
      - EXPORT_REPORT_PDF_SECONDARY_COLOR=${EXPORT_REPORT_PDF_SECONDARY_COLOR}
      - EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_1=${EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_1}
      - EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_2=${EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_2}
      - EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_3=${EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_3}
      - EXPORT_REPORT_PDF_COMPANY_PHONE_NUMBER=${EXPORT_REPORT_PDF_COMPANY_PHONE_NUMBER}
      - EXPORT_REPORT_PDF_COMPANY_EMAIL=${EXPORT_REPORT_PDF_COMPANY_EMAIL}
      - EXPORT_REPORT_PDF_COMPANY_WEBSITE=${EXPORT_REPORT_PDF_COMPANY_WEBSITE}
      - EXPORT_REPORT_PDF_INDICATORS_ONLY=${EXPORT_REPORT_PDF_INDICATORS_ONLY}
      - EXPORT_REPORT_PDF_DEFANG_URLS=${EXPORT_REPORT_PDF_DEFANG_URLS}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

