services:
  connector-cpe:
    image: opencti/connector-cpe:rolling
    env_file: "../envs/connector-cpe.env"
    environment:
      - OPENCTI_URL=${OPENCTI_BASE_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_CPE_ID}
      - CONNECTOR_TYPE=${CONNECTOR_CPE_TYPE}
      - CONNECTOR_NAME=${CONNECTOR_CPE_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_CPE_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_CPE_LOG_LEVEL}
      - CPE_BASE_URL=${CONNECTOR_CPE_CPE_BASE_URL}
      - NIST_API_KEY=${CONNECTOR_CPE_NIST_API_KEY}
      - CPE_INTERVAL=${CONNECTOR_CPE_CPE_INTERVAL}
    restart: always
    depends_on:
      opencti:
        condition: service_healthy

